wtf:
  colors:
    background: "black"
    border:
      focusable: "crimson"
      focused: "red"
      normal: "cyan"

  grid:
    columns: [35, 35, 40, 40, 40, 50]
    rows: [4, 9, 12, 10, 8, 14, 3]
  openFileUtil: open
  refreshInterval: 10
  term: "xterm-256color"

  mods:
    # [1-1 æ¬¢è¿ä¿¡æ¯]
    textfile:
      enabled: true
      filePath: "/Users/escape/.config/wtf/awesome.info"
      position:
        top: 0
        left: 0
        height: 1
        width: 6
      refreshInterval: 10000

    # [2-1 å¤©æ°”é¢„æŠ¥]
    prettyweather:
      enabled: true
      city: "XiAn China"
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 1800
      unit: "c"
      view: 0
      language: "en"

    # [2-2 ä¸–ç•Œæ—¶é—´]
    clocks:
      colors:
        rows:
          even: "chartreuse"
          odd: "lightblue"
      enabled: true
      locations:
        Beijing: "Asia/Shanghai"
        Shanghai: "Asia/Shanghai"
        Dubai: "Asia/Dubai"
        New York: "America/New York"
        Toronto: "America/Toronto"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 30
      sort: "alphabetical"

    # [2-3 è´§å¸æ±‡ç‡]
    exchangerates:
      enabled: true
      focusable: false
      position:
        top: 1
        left: 2
        width: 1
        height: 1
      precision: 3
      rates:
        CAD:
          - "USD"
          - "EUR"
        USD:
          - "CAD"
        EUR:
          - "CAD"
      title: "ğŸ’° Rates"

    # [2-4 ç”µæ± çŠ¶å†µ]
    power:
      enabled: true
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      refreshInterval: 180

    # [2-5 ç½‘ç»œçŠ¶å†µ]
    security:
      enabled: true
      position:
        top: 1
        left: 4
        height: 1
        width: 1
      refreshInterval: 3600

    # [2-6 IPåœ°å€ä¿¡æ¯]
    ipinfo:
      colors:
        name: red
        value: white
      enabled: true
      position:
        top: 1
        left: 5
        height: 1
        width: 1
      refreshInterval: 150

    # [3-1 ç³»ç»Ÿä¿¡æ¯]
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true

    # [3-2 æ–°é—»èµ„è®¯]
    hackernews:
      enabled: true
      numberOfStories: 20
      position:
        top: 2
        left: 2
        height: 2
        width: 2
      storyType: top
      refreshInterval: 900

    # [3-3 æ–°é—»èµ„è®¯]
    subreddit:
      enabled: true
      numberOfPosts: 10
      position:
        top: 2
        left: 4
        height: 2
        width: 2
      refreshInterval: 900
      sortOrder: top
      subreddit: "news"
      topTimePeriod: month

    # [4-1 ä»»åŠ¡è®¡åˆ’]
    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 3
        left: 0
        height: 2
        width: 2
      refreshInterval: 1800

    # [5-1 é¡¹ç›®ç›‘æ§]
    git:
      commitCount: 5
      commitFormat: "[forestgreen]%h [orange]%cd [white]%s [tomato]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 5
        left: 0
        height: 1
        width: 2
      refreshInterval: 10
      repositories:
      - "/Users/escape/Fuckcode/github/DotFiles"

    # [5-2 è®¢é˜…ä¿¡æ¯]
    feedreader:
      enabled: true
      feeds:
      - https://news.ycombinator.com/rss
      - https://rss.cbc.ca/lineup/topstories.xml
      feedLimit: 10
      position:
        top: 4
        left: 2
        height: 2
        width: 4
      refreshInterval: 14400

    # [7-1 çŠ¶æ€ä¿¡æ¯]
    status:
      enabled: true
      position:
        top: 6
        left: 0
        height: 1
        width: 6
      refreshInterval: 1
